config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  resources :posts
  root "posts#index"
  resources :users
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 30}
  validates :body, presence: true, length: {minimum: 3, maximum: 300}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :posts
  validates :username, presence: true, length: {minimum:3, maximum:35}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {minimum:3, maximum:40}, 
  uniqueness: {case_sensitive: false},
  format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all  
  end

  def new
    @post = Post.new
  end 

  def create
    @post = Post.new(params.require(:post).permit!)
    @post.user = User.first
    if @post.save
      flash.now[:notice]= "The post was created Successfully"
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params.require(:post).permit!)
      flash[:notice]= "Post Updated succeffully"
    else 
      render :edit, status: :unprocessable_entity
    end 
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice]= "You have been logged in"
      redirect_to user
    else
      flash.now[:alert]= "Lol, scammer"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id]= nil
    flash[:notice]= "You have been logged out"
    redirect_to login_path
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice]= "Welcome to Knots Solutions, #{@user.username}"
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(update_params)
      flash[:notice]= "Edited successfully, #{@user.username}"
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end




  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def update_params
    params.require(:user).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
   end
 
   def logged_in?
     !!current_user
   end
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_messages.html.erb
<% if obj.errors.any? %>
<h3>There are some error that prohibited <%= obj.class.name.downcase %> to create a post</h3>
<ul>
 <% obj.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignmentApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'layouts/messages', obj: @post %>

<%= form_with(model: @post) do |f| %>
  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :body %>
  <%= f.text_field :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/posts/edit.html.erb
<h4>Edit Post</h4>
<%= render 'form' %>

<%= link_to "Back to Listings", posts_path %>

app/views/posts/index.html.erb
<h1>Post Lisitng Page</h1>

<h2><%=  "Welcome to the club, #{current_user.username}"  if logged_in? %></h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan= "4">Information</th>
    </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <% if post.user == current_user && logged_in? %>
      <td> <%= link_to "Edit Post", edit_post_path(post)  %></td>
      <td> <%= link_to "Delete", post_path(post), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' } %></td>
      <td> <%= link_to "Show Post", post_path(post) %></td>

        <% else %>
      <td> <%= link_to "Show Post", post_path(post) %></td>
      <% end %>
      <td> <%= post.user.username if post.user %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New Post", new_post_path %>
<% if logged_in? %>
  <%= link_to "Logout ", logout_path, data: {"turbo-method": :delete} %>
    <% else %>
  <%= link_to "login", login_path %>
  <%= link_to "Signup", signup_path %>
<% end %>
  

app/views/posts/new.html.erb
<h1>New Form for Posts</h1>


<%= render 'form' %>

<%= link_to "Back to Listings", posts_path %>

app/views/posts/show.html.erb
<h1>Show Post</h1>

<p><strong>Title: </strong><%= @post.title %></p>
<p><strong>Description: </strong><%= @post.body %></p>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/users/_form.html.erb
<%= render 'layouts/messages', obj: @user %>

<%= form_with(model: @user) do |f| %>
  <p>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Enter a unique Username" %>
  </p>
  <p>
  <%= f.label :email %>
  <%= f.email_field :email, placeholder: "Enter your Email" %>
  </p>
    <p>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Enter your Password" %>
  </p>

  <p>
    <%= f.submit(@user.new_record? ? "Signup" : "Update account") %>
  </p>
  
<% end %>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/index.html.erb
<h1>Tweeters</h1>

<div>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan= "3">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td> <%= link_to "Edit user", edit_user_path(user)  %></td>
      <td> <%= link_to "Show user", user_path(user) %></td>
      <td> <%= time_ago_in_words(user.created_at) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/new.html.erb
<h1>Signup Form</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div>
  <h1>Show User</h1>

<p><strong>Title: </strong><%= @user.username %></p>
<p><strong>Description: </strong><%= @user.email %></p>
</div>


<div>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan= "3">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @user.posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td> <%= link_to "Edit Post", edit_post_path(post)  %></td>
      <td> <%= link_to "Show Post", post_path(post) %></td>
      <td> <%= time_ago_in_words(post.created_at) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>